### ISSUE TITLE
Is the `name` parameter of `ElfBinary` necessary?

### ISSUE THREAD

**Issue by toku-sa-n** [gz/rust-elfloader#17]
The parameter is used only in the `fmt::Debug` implementation. The users can print the name of the ELF binary along with the debug output of `ElfBinary` if necessary. Can the parameter be removed?

**Comment by gz** [comment]
Hi @toku-sa-n

Yes agreed that information doesn't have to be part of the ElfBinary. Feel free to submit a pull request that removes it. Is there a particular reason why it's inconvenient?
