### ISSUE TITLE
Will RISC-V be supported?

### ISSUE THREAD

**Issue by YdrMaster** [gz/rust-elfloader#32]

**Comment by gz** [comment]
Hi yes I'd be happy to have that supported. Probably the only thing that needs to happen is for someone to add the relocation types for RISC-V similar to [how it was done for aarch64](https://github.com/gz/rust-elfloader/commit/31a3b1477162ff75d073b6e23360ff406cbad9cb) and adding binaries+tests. Do you want to give it a try?

**Comment by YdrMaster** [comment]
I'm a new beginner for kernel developing, looking for a elf crate... Maybe I'll try to contribute later, after I know the loader enough.
