### ISSUE TITLE
Can this program load ELF So files and execute them?

### ISSUE THREAD

**Issue by roterdam** [gz/rust-elfloader#5]
I've been looking for a program that can load and execute shared SO files.

Your program handles all the GOT/PLT issues and relocating all of that to make machine code runnable?

**Comment by gz** [comment]
@roterdam I've used elfloader sucessfully for loading statically linked binaries (see https://github.com/gz/bespin/blob/master/kernel/arch/x86_64/mod.rs#L143). However, it is still far from a complete elfloader and does not support all cases. I'm happy for any patches that improve the functionality etc.
