### ISSUE TITLE
BSS and empty sections

### ISSUE THREAD

**Issue by vinaychandra** [gz/rust-elfloader#9]
How are `bss` sections loaded?
Just `allocate` is called or is `load` also called with zero values?
The reason is that zeroing of memory is not needed in case load is called. 

Can you please call this out in docs / examples?

**Comment by gz** [comment]
The `allocate` function is called for every program header of type `LOAD`.
`load` will not be called for something like `bss` so the client has to ensure the memory is zeroed in `allocate`. The idea is that `allocate` reserves the memory and zeroes it and `load` fills in the relevant region (.text, etc).

The easiest thing to visualize what happens it is probably run `readelf --program-headers` on the binary you're trying to load and then correspond the information with the actual calls to the elfloader trait.
